### ISSUE TITLE
recruitment - stream time

### ISSUE THREAD

**Issue by DamiXioR** [coders-school/recruitment#1]
REKRUTACJA

Start 00:04:50
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=290s
Agenda 00:07:38
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=458s
Zarobki programistów 00:08:13
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=493s
CV programisty 00:36:50
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=2210s
Co jest dobre 00:50:03
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=3003s
Czego unikać 00:58:27
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=3507s
CV Łukasz Ziobroń 01:11:58
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=4318s
Przerwa 01:41:11
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=6071s
Po przerwie 01:55:24
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=6924s
Porady rekrutacyjne 01:56:47
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=7007s
Pytania do pracodawcy 02:33:03
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=9183s
Przykładowe pytania rekrutacyjne 02:42:48
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=9768s
Praca domowa 02:55:40 
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=10540s
Pre work 02:55:40 
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=10540s
Post work 03:00:48
https://www.youtube.com/watch?v=XpCaAhUcYrI&t=10848s

**Comment by ziobron** [comment]
{ "requirement_ids": [4069] }
5 XP za utworzenie spisu treści do lekcji na YouTube (4069)
